---
- hosts: master
  vars_files:
  - vars/nibbler-tests.yml

  roles:
  - common
  - hdfs-common
  - hdfs-namenode
  - mesos-common
  - zookeeper
  - mesos-master
  - nibbler
  - nibbler-tests

- hosts: slaves

  roles:
  - common
  - hdfs-common
  - mesos-common
  - mesos-slave
  - hdfs-datanode
