---
- name: Provision master
  hosts: tag_type_master 
  remote_user: ubuntu
  sudo: true
  vars_files:
  - vars/hdfs.yml

  roles:
  - common
  - hdfs-common
  - hdfs-namenode
  - mesos-common
  - zookeeper
  - mesos-master
  - nibbler

- name: Restart master
  hosts: tag_type_master
  remote_user: ubuntu
  sudo: true
  tasks:
  - command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true

- name: Waiting for master to come back
  hosts: localhost
  tasks:
  - local_action: wait_for host={{ hostvars[groups['tag_type_master'][0]].ec2_public_dns_name }}
                  state=started port=22
    sudo: false

- name: Provision slaves
  sudo: true
  remote_user: ubuntu
  hosts: tag_type_slave
  vars_files:
  - vars/hdfs.yml

  roles:
  - common
  - hdfs-common
  - hdfs-datanode
  - mesos-common
  - mesos-slave

- name: Restart slaves
  hosts: tag_type_slave
  remote_user: ubuntu
  sudo: true
  tasks:
  - command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true

- name: Waiting for slaves to come back
  hosts: localhost
  tasks: 
  - local_action: wait_for host={{ item.ec2_public_dns_name }}
                  state=started port=22
    sudo: false
    with_items: groups['tag_type_slave']

- name: Provision tests on master
  hosts: master
  vars_files:
  - vars/hdfs.yml

  roles:
  - nibbler-tests

