---
- hosts: master
  vars_files:
  - vars/nibbler-tests.yml
  - vars/hdfs.yml

  roles:
  - common
  - hdfs-common
  - hdfs-namenode
  - mesos-common
  - zookeeper
  - mesos-master
  - nibbler
  - nibbler-tests
