---
- name: Disable mesos master - override master init file
  file: path=/etc/init/mesos-master.override state=touch

- name: Disable mesos master - manual line
  lineinfile: dest=/etc/init/mesos-master.override line="manual" state="present"

- name: Mesos executor timeout
  template: dest=/etc/mesos-slave/executor_registration_timeout src=../templates/executor_registration_timeout

- name: Remove default zk configuration
  file: path=/etc/mesos/zk state=absent

- name: Mesos zookeeper URI
  lineinfile: dest=/etc/default/mesos line="MASTER=zk://{{ hostvars[groups['tag_type_master'][0]]['ansible_hostname'] }}:2181/mesos" state="present" regexp="MASTER=(.*)"

- name: Setup mesos-slave IP address
  template: backup=yes src=../templates/mesos-slave dest=/etc/default/mesos-slave
