---
- name: Disable mesos slave - override init file
  file: path=/etc/init/mesos-slave.override state=file

- name: Disable mesos slave - manual line
  lineinfile: dest=/etc/init/mesos-slave.override line="manual" state="present"

- name: Setup mesos-master IP address
  template: backup=yes src=../templates/mesos-master dest=/etc/default/mesos-master

- name: Register in zookeeper
  lineinfile: dest=/etc/default/mesos regexp="ZK=(.*)" state="absent"
  lineinfile: dest=/etc/default/mesos line="ZK=zk://localhost:2181/mesos" state="present"
